export const ASSETS = [
  {
    id: 0,
    title: "FAIRMONT - LOGO - WHITE",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/05/Factsheet-Individual-ESP-1.pdf",
    preview: "",
    type: "events",
    filetype: "pdf",
  },
  {
    id: 1,
    title: "FAIRMONT - LOGO - WHITE",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/5351_230301_Fairmont-scaled.jpg",
    preview: "",
    type: "events",
    filetype: "image",
  },
  {
    id: 2,
    title: "FAIRMONT - LOGO - WHITE",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/5351_230301_Fairmont-scaled.jpg",
    preview: "",
    type: "events",
    filetype: "image",
  },
  {
    id: 3,
    title: "FAIRMONT - LOGO - WHITE",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/5351_230301_Fairmont-scaled.jpg",
    preview: "",
    type: "events",
    filetype: "image",
  },
  {
    id: 4,
    title: "FAIRMONT - LOGO - WHITE",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/5351_230301_Fairmont-scaled.jpg",
    preview: "",
    type: "events",
    filetype: "video",
  },
  {
    id: 5,
    title: "FAIRMONT - LOGO - WHITE",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/5351_230301_Fairmont-scaled.jpg",
    preview: "",
    type: "events",
    filetype: "image",
  },
  {
    id: 6,
    title: "FAIRMONT - LOGO - WHITE",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/5351_230301_Fairmont-scaled.jpg",
    preview: "",
    type: "events",
    filetype: "image",
  },
];
