export const ASSETS = [
  {
    id: 0,
    title: "Factsheet-Individual-ESP-1",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/05/Factsheet-Individual-ESP-1.pdf",
    preview:
      "https://www.fairmont-mayakoba.com/content/uploads/2024/08/Factsheet-Individual-ESP-1.png",
    type: "factsheet",
    filetype: "other",
  },
  {
    id: 1,
    title: "MYK_Aerial01",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/MYK_Aerial01-scaled.jpg",
    preview: "",
    type: "pool",
    filetype: "img",
  },
  {
    id: 2,
    title: "MYK_Aerial02V2",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/MYK_Aerial02V2-scaled.jpg",
    preview: "",
    type: "pool",
    filetype: "img",
  },
  {
    id: 3,
    title: "MYK_Aerial03V2",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/MYK_Aerial03V2-scaled.jpg",
    preview: "",
    type: "pool",
    filetype: "img",
  },
  {
    id: 4,
    title: "MYK_Aerial04V2",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/MYK_Aerial04V2-scaled.jpg",
    preview: "",
    type: "pool",
    filetype: "img",
  },
  {
    id: 5,
    title: "MYK_Aerial05",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/MYK_Aerial05-scaled.jpg",
    preview: "",
    type: "pool",
    filetype: "img",
  },
  {
    id: 6,
    title: "MYK_Aerial06",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/MYK_Aerial06-scaled.jpg",
    preview: "",
    type: "pool",
    filetype: "img",
  },
  {
    id: 7,
    title: "Riviera MYK_351",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/Riviera-MYK_351-scaled.jpg",
    preview: "",
    type: "events",
    filetype: "img",
  },
  {
    id: 8,
    title: "Riviera MYK_352",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/Riviera-MYK_352-scaled.jpg",
    preview: "",
    type: "events",
    filetype: "img",
  },
  {
    id: 9,
    title: "Riviera MYK_353",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/Riviera-MYK_353-scaled.jpg",
    preview: "",
    type: "events",
    filetype: "img",
  },
  {
    id: 10,
    title: "Terraza Lawn MYK_350",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/Terraza-Lawn-MYK_350-scaled.jpg",
    preview: "",
    type: "resort",
    filetype: "img",
  },
  {
    id: 11,
    title: "Factsheet Individual ING",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/05/Factsheet-Individual-ING-1.pdf",
    preview:
      "https://www.fairmont-mayakoba.com/content/uploads/2024/08/Factsheet-Individual-ING-1.png",
    type: "factsheet",
    filetype: "other",
  },
  {
    id: 12,
    title: "Factsheet Individual Extendido ING",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/05/Factsheet-Fairmont-ENG-2024.pdf",
    preview:
      "https://www.fairmont-mayakoba.com/content/uploads/2024/08/Factsheet-Fairmont-ENG-2024.png",
    type: "factsheet",
    filetype: "other",
  },
  {
    id: 13,
    title: "Leisure 2024",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/05/press-leisure-2024-3.pdf",
    preview:
      "https://www.fairmont-mayakoba.com/content/uploads/2024/08/press-leisure-2024-3.png",
    type: "factsheet",
    filetype: "other",
  },
  {
    id: 14,
    title: "Políticas de sustentabilidad 2024 Español",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/05/Politicas-de-sustentabilidad_esp.pdf",
    preview:
      "https://www.fairmont-mayakoba.com/content/uploads/2024/08/Politicas-de-sustentabilidad_esp.png",
    type: "factsheet",
    filetype: "other",
  },
  {
    id: 15,
    title: "Políticas de sustentabilidad 2024 Inglés",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/05/Politicas-de-sustentabilidad_ing.pdf",
    preview:
      "https://www.fairmont-mayakoba.com/content/uploads/2024/08/Politicas-de-sustentabilidad_ing.png",
    type: "factsheet",
    filetype: "other",
  },
  {
    id: 16,
    title: "Presentación de bodas 2024 inglés",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/05/Wedding-presentation-ENG-2024.pdf",
    preview:
      "https://www.fairmont-mayakoba.com/content/uploads/2024/08/Wedding-presentation-ENG-2024.png",
    type: "weddings",
    filetype: "other",
  },
  {
    id: 17,
    title: "Brochure Bodas 2023 en español",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/05/Brochure-weddings-Esp.pdf",
    preview:
      "https://www.fairmont-mayakoba.com/content/uploads/2024/08/Brochure-weddings-Esp.png",
    type: "weddings",
    filetype: "other",
  },
  {
    id: 18,
    title: "Brochure Bodas 2023 en inglés",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/05/Brochure-Weddings-ENG.pdf",
    preview:
      "https://www.fairmont-mayakoba.com/content/uploads/2024/08/Brochure-Weddings-ENG.png",
    type: "weddings",
    filetype: "other",
  },
  {
    id: 19,
    title: "Brochure Mice 2024 en español",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/05/Brochure-MICE-SPA.pdf",
    preview:
      "https://www.fairmont-mayakoba.com/content/uploads/2024/08/Brochure-MICE-ENG.png",
    type: "brochure",
    filetype: "other",
  },
  {
    id: 20,
    title: "Brochure Mice 2024 en inglés",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/05/Brochure-MICE-ENG.pdf",
    preview:
      "https://www.fairmont-mayakoba.com/content/uploads/2024/08/Brochure-MICE-ENG.png",
    type: "brochure",
    filetype: "other",
  },
  {
    id: 21,
    title: "Factsheet Spa 2024 en inglés",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/05/FactSheet-Spa-2024_ING.pdf",
    preview:
      "https://www.fairmont-mayakoba.com/content/uploads/2024/08/FactSheet-Spa-2024_ING.png",
    type: "factsheet",
    filetype: "other",
  },
  {
    id: 22,
    title: "Factsheet Spa 2024 en español",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/05/FactSheet-Spa-2024-ESP.pdf",
    preview:
      "https://www.fairmont-mayakoba.com/content/uploads/2024/08/FactSheet-Spa-2024_ING.png",
    type: "factsheet",
    filetype: "other",
  },
  {
    id: 23,
    title: "Factsheet Kids Club 2024 en inglés",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/05/FactSheet-Kids-2024-ING-1.pdf",
    preview:
      "https://www.fairmont-mayakoba.com/content/uploads/2024/08/FactSheet-Kids-2024-ING-1.png",
    type: "factsheet",
    filetype: "other",
  },
  {
    id: 24,
    title: "Factsheet Kids Club 2024 en español",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/05/FactSheet-Kids-2024-ESP-1.pdf",
    preview:
      "https://www.fairmont-mayakoba.com/content/uploads/2024/08/FactSheet-Kids-2024-ING-1.png",
    type: "factsheet",
    filetype: "other",
  },
  {
    id: 25,
    title: "4673_230228_Fairmont-scaled",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/4673_230228_Fairmont-scaled.jpg",
    preview: "",
    type: "residences",
    filetype: "img",
  },
  {
    id: 26,
    title: "4583_230228_Fairmont-scaled",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/4583_230228_Fairmont-scaled.jpg",
    preview: "",
    type: "residences",
    filetype: "img",
  },
  {
    id: 27,
    title: "4607_230228_Fairmont-scaled",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/4607_230228_Fairmont-scaled.jpg",
    preview: "",
    type: "residences",
    filetype: "img",
  },
  {
    id: 28,
    title: "4616_230228_Fairmont-scaled",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/4616_230228_Fairmont-scaled.jpg",
    preview: "",
    type: "residences",
    filetype: "img",
  },
  {
    id: 29,
    title: "4626_230228_Fairmont-scaled",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/4626_230228_Fairmont-scaled.jpg",
    preview: "",
    type: "residences",
    filetype: "img",
  },
  {
    id: 30,
    title: "4656_230228_Fairmont-scaled",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/4656_230228_Fairmont-scaled.jpg",
    preview: "",
    type: "residences",
    filetype: "img",
  },
  {
    id: 31,
    title: "4689_230228_Fairmont-scaled",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/4689_230228_Fairmont-scaled.jpg",
    preview: "",
    type: "residences",
    filetype: "img",
  },
  {
    id: 32,
    title: "4696_230228_Fairmont-scaled",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/4696_230228_Fairmont-scaled.jpg",
    preview: "",
    type: "residences",
    filetype: "img",
  },
  {
    id: 33,
    title: "4234_230227_Fairmont-scaled",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/4234_230227_Fairmont-scaled.jpg",
    preview: "",
    type: "residences",
    filetype: "img",
  },
  {
    id: 34,
    title: "4246_230227_Fairmont-scaled",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/4246_230227_Fairmont-scaled.jpg",
    preview: "",
    type: "residences",
    filetype: "img",
  },
  {
    id: 35,
    title: "4263_230227_Fairmont",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/4263_230227_Fairmont-scaled.jpg",
    preview: "",
    type: "residences",
    filetype: "img",
  },
  {
    id: 36,
    title: "4272_230227_Fairmont-scaled",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/4272_230227_Fairmont-scaled.jpg",
    preview: "",
    type: "residences",
    filetype: "img",
  },
  {
    id: 37,
    title: "4284_230227_Fairmont",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/4284_230227_Fairmont-scaled.jpg",
    preview: "",
    type: "residences",
    filetype: "img",
  },
  {
    id: 38,
    title: "4293_230227_Fairmont-scaled",
    url: "https://www.fairmont-mayakoba.com/content/uploads/2024/08/4293_230227_Fairmont-scaled.jpg",
    preview: "",
    type: "residences",
    filetype: "img",
  },
];
